#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh


bspc monitor -d 1 2 3 4 5 6 7 8

#bspc config border_width         2
#bspc config window_gap          

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#### BSPWM configuration ####
bspc config border_radius                15
bspc config border_width                  1
bspc config window_gap                    10
bspc config top_padding                   -5
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
#bspc config normal_border_color           "#003566"
bspc config active_border_color	      "#976ed7"
bspc config focused_border_color	      "#4c5265"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a chromium state=floating
bspc rule -a nautilus state=floating
#bspc rule -a firefox state = floating follow=off
bspc rule -a iwgtk state=floating follow=off rectangle=500x500+1300+100
bspc rule -a TelegramDesktop desktop='^7' state=floating follow=on rectangle=500x1000+1400+40
bspc rule -a Nemo state=floating follow=off rectangle=800x800
bspc rule -a org.gnome.Nautilus state=floating follow=off rectangle=800x800+100+100
bspc rule -a Shutter state=floating follow=off rectangle=500x500+1300+100
bspc rule -a Pavucontrol state=floating follow=off rectangle=500x500+1300+30
bspc rule -a Yad state=floating rectangle=300x300+1100+25
bspc rule -a CoreImage state=floating


